[package]
name = "shiinobi"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
reqwest = "0.12.5"
scraper = "0.20.0"
tokio = { version = "1.39.2", features = ["full"] }
tokio-macros = "2.4.0"
