[package]
name = "shiinobi"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.13"
reqwest = "0.12.5"
scraper = "0.20.0"
tokio = { version = "1.39.2", features = ["full"] }
tokio-macros = "2.4.0"
